### ISSUE TITLE
Keyword as argument name is syntax error

### ISSUE THREAD

**Issue by pocke** [ruby/ruby-signature#154]
# Problem

Currently, RBS does not allow a keyword as an argument name.

```ruby
class C
  # "type" is a keyword in RBS, and a keyword is not allowed at here (var_name_opt).
  # So it is syntax error.
  def foo: (untyped type) -> void

  # It is also syntax error.
  def foo: (type: untyped type) -> void

  # It is not a syntax error.
  def foo: (type: untyped) -> void
end
```

I found this problem while #153 .
We have the following Ruby code, and `rbs prototype rb` command generates a code with synax error from it.

```ruby
class C
  def foo(type:)
  end
end
```

# Solution

I have several ideas to fix it.

* Allow keyword as an argument name.
  * ```diff
    diff --git a/lib/ruby/signature/parser.y b/lib/ruby/signature/parser.y
    index 2c8475e..654b232 100644
    --- a/lib/ruby/signature/parser.y
    +++ b/lib/ruby/signature/parser.y
    @@ -941,7 +941,7 @@ rule
           }
     
       var_name_opt:
    -    | tLIDENT | tINTERFACEIDENT
    +    | tLIDENT | tINTERFACEIDENT | identifier_keywords
     
       qualified_name:
           namespace simple_name {
    ```
  * It works well and does not increase conflicts.
  * But I'm wondering if it conflicts in the future.
* Allow escaping for argument name, like method name.
  * ``def foo: (untyped `type`) -> void``
  * I like this idea.
* Fix `rbs prototype rb` command to avoid generating syntax error code.
  * e.g. replacing `type` with `_type`
  * It works for `rbs prototype rb`, but I guess we'd like to use `type` as argument name.
  * So I think it is not a good idea. 



What do you think about these solution ideas?

**Comment by soutaro** [comment]
I think allowing to escape argument name is good option.
